services:
  db:
    image: postgres:15-alpine
    container_name: akvinz_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: akvinz
    ports:
      - '5436:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
